# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gluvnui.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
import MainGUI

class Ui_MainWindow(object):
    
    def PlayAction_test(self):
        
        keyrange = ['C3', 'Db3', 'D3', 'Eb3', 'E3', 'F3', 'Gb3', 'G3', 'Ab3', 'A3', 'Bb3', 'B3', 'C4']
        pnotes = ['C4', 'D4', 'E4', 'G4', 'A4']
        fnotes = ['C4', 'D4', 'E4', 'G4', 'A4']

        if(self.pressurebox.isChecked()):
            PressKey = [self.ButtonC.isChecked(), 
            self.ButtonDb.isChecked(), 
            self.ButtonD.isChecked(), 
            self.ButtonEb.isChecked(), 
            self.ButtonE.isChecked(), 
            self.ButtonF.isChecked(), 
            self.ButtonGb.isChecked(), 
            self.ButtonG.isChecked(), 
            self.ButtonAb.isChecked(), 
            self.ButtonA.isChecked(), 
            self.ButtonBb.isChecked(), 
            self.ButtonB.isChecked(), 
            self.ButtonC2.isChecked()]
            indp = [i for i, x in enumerate(PressKey) if x]
            pnotes = [keyrange[i] for i in indp]
            print(PressKey)
            print(indp)
            print(pnotes)

        if(self.flexbox.isChecked()):
            FlexKey = [self.ButtonC_2.isChecked(), 
            self.ButtonDb_2.isChecked(), 
            self.ButtonD_2.isChecked(), 
            self.ButtonEb_2.isChecked(), 
            self.ButtonE_2.isChecked(), 
            self.ButtonF_2.isChecked(), 
            self.ButtonGb_2.isChecked(), 
            self.ButtonG_2.isChecked(), 
            self.ButtonAb_2.isChecked(), 
            self.ButtonA_2.isChecked(), 
            self.ButtonBb_2.isChecked(), 
            self.ButtonB_2.isChecked(), 
            self.ButtonC2_2.isChecked()]
            indp = [i for i, x in enumerate(FlexKey) if x]
            fnotes = [keyrange[i] for i in indp]
        
        print('asdjfkjghaf')    
        MainGUI.main(self.simulationbox.isChecked(), self.pressurebox.isChecked(), self.flexbox.isChecked(), self.chordbox.isChecked(), pnotes, fnotes)


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(60, 10, 671, 391))
        self.groupBox.setObjectName("groupBox")
        self.ButtonEb_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonEb_2.setGeometry(QtCore.QRect(270, 190, 41, 51))
        self.ButtonEb_2.setCheckable(True)
        self.ButtonEb_2.setObjectName("ButtonEb_2")
        self.ButtonC = QtWidgets.QPushButton(self.groupBox)
        self.ButtonC.setGeometry(QtCore.QRect(210, 100, 41, 61))
        self.ButtonC.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonC.setCheckable(True)
        self.ButtonC.setObjectName("ButtonC")
        self.ButtonAb = QtWidgets.QPushButton(self.groupBox)
        self.ButtonAb.setGeometry(QtCore.QRect(430, 60, 41, 51))
        self.ButtonAb.setCheckable(True)
        self.ButtonAb.setObjectName("ButtonAb")
        self.ButtonB = QtWidgets.QPushButton(self.groupBox)
        self.ButtonB.setGeometry(QtCore.QRect(450, 100, 41, 61))
        self.ButtonB.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonB.setCheckable(True)
        self.ButtonB.setObjectName("ButtonB")
        self.ButtonC2_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonC2_2.setGeometry(QtCore.QRect(490, 230, 41, 61))
        self.ButtonC2_2.setMinimumSize(QtCore.QSize(21, 0))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        self.ButtonC2_2.setPalette(palette)
        self.ButtonC2_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ButtonC2_2.setCheckable(True)
        self.ButtonC2_2.setAutoDefault(False)
        self.ButtonC2_2.setDefault(False)
        self.ButtonC2_2.setFlat(False)
        self.ButtonC2_2.setObjectName("ButtonC2_2")
        self.confchord_1 = QtWidgets.QRadioButton(self.groupBox)
        self.confchord_1.setGeometry(QtCore.QRect(140, 340, 141, 20))
        self.confchord_1.setObjectName("confchord_1")
        self.ButtonC_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonC_2.setGeometry(QtCore.QRect(210, 230, 41, 61))
        self.ButtonC_2.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonC_2.setCheckable(True)
        self.ButtonC_2.setObjectName("ButtonC_2")
        self.ButtonEb = QtWidgets.QPushButton(self.groupBox)
        self.ButtonEb.setGeometry(QtCore.QRect(270, 60, 41, 51))
        self.ButtonEb.setCheckable(True)
        self.ButtonEb.setObjectName("ButtonEb")
        self.ButtonGb = QtWidgets.QPushButton(self.groupBox)
        self.ButtonGb.setGeometry(QtCore.QRect(390, 60, 41, 51))
        self.ButtonGb.setCheckable(True)
        self.ButtonGb.setObjectName("ButtonGb")
        self.ButtonC2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonC2.setGeometry(QtCore.QRect(490, 100, 41, 61))
        self.ButtonC2.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonC2.setCheckable(True)
        self.ButtonC2.setObjectName("ButtonC2")
        self.flexbox = QtWidgets.QCheckBox(self.groupBox)
        self.flexbox.setGeometry(QtCore.QRect(50, 170, 151, 20))
        self.flexbox.setObjectName("flexbox")
        self.ButtonG_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonG_2.setGeometry(QtCore.QRect(370, 230, 41, 61))
        self.ButtonG_2.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonG_2.setCheckable(True)
        self.ButtonG_2.setObjectName("ButtonG_2")
        self.chordbox = QtWidgets.QCheckBox(self.groupBox)
        self.chordbox.setGeometry(QtCore.QRect(50, 310, 241, 20))
        self.chordbox.setObjectName("chordbox")
        self.ButtonB_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonB_2.setGeometry(QtCore.QRect(450, 230, 41, 61))
        self.ButtonB_2.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonB_2.setCheckable(True)
        self.ButtonB_2.setObjectName("ButtonB_2")
        self.ButtonDb_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonDb_2.setGeometry(QtCore.QRect(230, 190, 41, 51))
        self.ButtonDb_2.setCheckable(True)
        self.ButtonDb_2.setObjectName("ButtonDb_2")
        self.ButtonF_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonF_2.setGeometry(QtCore.QRect(330, 230, 41, 61))
        self.ButtonF_2.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonF_2.setCheckable(True)
        self.ButtonF_2.setAutoDefault(False)
        self.ButtonF_2.setDefault(False)
        self.ButtonF_2.setFlat(False)
        self.ButtonF_2.setObjectName("ButtonF_2")
        self.pressurebox = QtWidgets.QCheckBox(self.groupBox)
        self.pressurebox.setGeometry(QtCore.QRect(50, 30, 181, 20))
        self.pressurebox.setObjectName("pressurebox")
        self.ButtonA = QtWidgets.QPushButton(self.groupBox)
        self.ButtonA.setGeometry(QtCore.QRect(410, 100, 41, 61))
        self.ButtonA.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonA.setCheckable(True)
        self.ButtonA.setObjectName("ButtonA")
        self.confchord_2 = QtWidgets.QRadioButton(self.groupBox)
        self.confchord_2.setGeometry(QtCore.QRect(140, 360, 141, 20))
        self.confchord_2.setObjectName("confchord_2")
        self.ButtonE = QtWidgets.QPushButton(self.groupBox)
        self.ButtonE.setGeometry(QtCore.QRect(290, 100, 41, 61))
        self.ButtonE.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonE.setCheckable(True)
        self.ButtonE.setObjectName("ButtonE")
        self.ButtonBb = QtWidgets.QPushButton(self.groupBox)
        self.ButtonBb.setGeometry(QtCore.QRect(470, 60, 41, 51))
        self.ButtonBb.setCheckable(True)
        self.ButtonBb.setObjectName("ButtonBb")
        self.ButtonF = QtWidgets.QPushButton(self.groupBox)
        self.ButtonF.setGeometry(QtCore.QRect(330, 100, 41, 61))
        self.ButtonF.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonF.setCheckable(True)
        self.ButtonF.setAutoDefault(False)
        self.ButtonF.setDefault(False)
        self.ButtonF.setFlat(False)
        self.ButtonF.setObjectName("ButtonF")
        self.ButtonD = QtWidgets.QPushButton(self.groupBox)
        self.ButtonD.setGeometry(QtCore.QRect(250, 100, 41, 61))
        self.ButtonD.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonD.setCheckable(True)
        self.ButtonD.setObjectName("ButtonD")
        self.ButtonGb_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonGb_2.setGeometry(QtCore.QRect(390, 190, 41, 51))
        self.ButtonGb_2.setCheckable(True)
        self.ButtonGb_2.setObjectName("ButtonGb_2")
        self.ButtonAb_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonAb_2.setGeometry(QtCore.QRect(430, 190, 41, 51))
        self.ButtonAb_2.setCheckable(True)
        self.ButtonAb_2.setObjectName("ButtonAb_2")
        self.ButtonDb = QtWidgets.QPushButton(self.groupBox)
        self.ButtonDb.setGeometry(QtCore.QRect(230, 60, 41, 51))
        self.ButtonDb.setCheckable(True)
        self.ButtonDb.setObjectName("ButtonDb")
        self.ButtonD_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonD_2.setGeometry(QtCore.QRect(250, 230, 41, 61))
        self.ButtonD_2.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonD_2.setCheckable(True)
        self.ButtonD_2.setObjectName("ButtonD_2")
        self.ButtonA_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonA_2.setGeometry(QtCore.QRect(410, 230, 41, 61))
        self.ButtonA_2.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonA_2.setCheckable(True)
        self.ButtonA_2.setObjectName("ButtonA_2")
        self.ButtonG = QtWidgets.QPushButton(self.groupBox)
        self.ButtonG.setGeometry(QtCore.QRect(370, 100, 41, 61))
        self.ButtonG.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonG.setCheckable(True)
        self.ButtonG.setObjectName("ButtonG")
        self.ButtonE_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonE_2.setGeometry(QtCore.QRect(290, 230, 41, 61))
        self.ButtonE_2.setMinimumSize(QtCore.QSize(21, 0))
        self.ButtonE_2.setCheckable(True)
        self.ButtonE_2.setObjectName("ButtonE_2")
        self.ButtonBb_2 = QtWidgets.QPushButton(self.groupBox)
        self.ButtonBb_2.setGeometry(QtCore.QRect(470, 190, 41, 51))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 170, 170))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(127, 127, 127))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        self.ButtonBb_2.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(False)
        self.ButtonBb_2.setFont(font)
        self.ButtonBb_2.setInputMethodHints(QtCore.Qt.ImhNone)
        self.ButtonBb_2.setCheckable(True)
        self.ButtonBb_2.setObjectName("ButtonBb_2")
        self.ButtonC.raise_()
        self.ButtonB.raise_()
        self.ButtonC2_2.raise_()
        self.confchord_1.raise_()
        self.ButtonC_2.raise_()
        self.ButtonC2.raise_()
        self.flexbox.raise_()
        self.ButtonG_2.raise_()
        self.chordbox.raise_()
        self.ButtonB_2.raise_()
        self.ButtonF_2.raise_()
        self.pressurebox.raise_()
        self.ButtonA.raise_()
        self.confchord_2.raise_()
        self.ButtonE.raise_()
        self.ButtonD.raise_()
        self.ButtonF.raise_()
        self.ButtonBb.raise_()
        self.ButtonDb.raise_()
        self.ButtonD_2.raise_()
        self.ButtonA_2.raise_()
        self.ButtonG.raise_()
        self.ButtonE_2.raise_()
        self.ButtonBb_2.raise_()
        self.ButtonC.raise_()
        self.ButtonB.raise_()
        self.ButtonC2_2.raise_()
        self.confchord_1.raise_()
        self.ButtonC_2.raise_()
        self.ButtonC2.raise_()
        self.flexbox.raise_()
        self.ButtonG_2.raise_()
        self.chordbox.raise_()
        self.ButtonB_2.raise_()
        self.ButtonF_2.raise_()
        self.pressurebox.raise_()
        self.ButtonA.raise_()
        self.confchord_2.raise_()
        self.ButtonE.raise_()
        self.ButtonBb.raise_()
        self.ButtonF.raise_()
        self.ButtonD.raise_()
        self.ButtonDb.raise_()
        self.ButtonD_2.raise_()
        self.ButtonA_2.raise_()
        self.ButtonG.raise_()
        self.ButtonE_2.raise_()
        self.ButtonBb_2.raise_()
        self.ButtonEb.raise_()
        self.ButtonAb.raise_()
        self.ButtonAb_2.raise_()
        self.ButtonDb_2.raise_()
        self.ButtonEb_2.raise_()
        self.ButtonGb.raise_()
        self.ButtonGb_2.raise_()
        self.simulationbox = QtWidgets.QCheckBox(self.centralwidget)
        self.simulationbox.setGeometry(QtCore.QRect(110, 440, 86, 20))
        self.simulationbox.setObjectName("simulationbox")
        self.stop_btn = QtWidgets.QPushButton(self.centralwidget)
        self.stop_btn.setGeometry(QtCore.QRect(660, 510, 113, 32))
        self.stop_btn.setObjectName("stop_btn")
        self.play_btn = QtWidgets.QPushButton(self.centralwidget)
        self.play_btn.setGeometry(QtCore.QRect(530, 510, 113, 32))
        self.play_btn.setObjectName("play_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())



        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Select Application"))
        self.ButtonEb_2.setText(_translate("MainWindow", "Eb"))
        self.ButtonC.setText(_translate("MainWindow", "C"))
        self.ButtonAb.setText(_translate("MainWindow", "Ab"))
        self.ButtonB.setText(_translate("MainWindow", "B"))
        self.ButtonC2_2.setText(_translate("MainWindow", "C2"))
        self.confchord_1.setText(_translate("MainWindow", "Configuration 1"))
        self.ButtonC_2.setText(_translate("MainWindow", "C"))
        self.ButtonEb.setText(_translate("MainWindow", "Eb"))
        self.ButtonGb.setText(_translate("MainWindow", "Gb"))
        self.ButtonC2.setText(_translate("MainWindow", "C2"))
        self.flexbox.setText(_translate("MainWindow", "5-Note Wind (Flex)"))
        self.ButtonG_2.setText(_translate("MainWindow", "G"))
        self.chordbox.setText(_translate("MainWindow", "Virtual Chords (Flex and IMU)"))
        self.ButtonB_2.setText(_translate("MainWindow", "B"))
        self.ButtonDb_2.setText(_translate("MainWindow", "Db"))
        self.ButtonF_2.setText(_translate("MainWindow", "F"))
        self.pressurebox.setText(_translate("MainWindow", "5-Note Piano (Pressure)"))
        self.ButtonA.setText(_translate("MainWindow", "A"))
        self.confchord_2.setText(_translate("MainWindow", "Configuration 2"))
        self.ButtonE.setText(_translate("MainWindow", "E"))
        self.ButtonBb.setText(_translate("MainWindow", "Bb"))
        self.ButtonF.setText(_translate("MainWindow", "F"))
        self.ButtonD.setText(_translate("MainWindow", "D"))
        self.ButtonGb_2.setText(_translate("MainWindow", "Gb"))
        self.ButtonAb_2.setText(_translate("MainWindow", "Ab"))
        self.ButtonDb.setText(_translate("MainWindow", "Db"))
        self.ButtonD_2.setText(_translate("MainWindow", "D"))
        self.ButtonA_2.setText(_translate("MainWindow", "A"))
        self.ButtonG.setText(_translate("MainWindow", "G"))
        self.ButtonE_2.setText(_translate("MainWindow", "E"))
        self.ButtonBb_2.setText(_translate("MainWindow", "Bb"))
        self.simulationbox.setText(_translate("MainWindow", "Simulation"))
        self.stop_btn.setText(_translate("MainWindow", "Stop"))
        self.play_btn.setText(_translate("MainWindow", "Play"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))




class Prog(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__();
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        self.ui.play_btn.clicked.connect(self.ui.PlayAction_test)

if __name__=='__main__':
    import sys
    Program =  QtWidgets.QApplication(sys.argv)
    MyProg = Prog()
    MyProg.show()
    sys.exit(Program.exec_())
